spring:
  profiles:
    include: aws, jwt, fcm

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: mysql

  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
#    org.springframework.security: trace

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json