spring:
  datasource:
    url: jdbc:mysql://fridge.chi4hxh1huos.ap-northeast-2.rds.amazonaws.com:3306/fridgeDB
    username: admin
    password: challenger
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
