spring:
  profiles:
    include: aws

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: mysql
  #        dialect: org.hibernate.dialect.MySQL57Dialect

  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: 35c21b3de74471b7fd035869767f0cdb0b6adc041c74d252a4913df64ff3d3ec
  access-token-validity-in-seconds: 1800 # 30분
  refresh-token-validity-in-seconds: 7200 # 2시간
